using System.Globalization;
using DeskBox.Models;

namespace DeskBox.Services;

public sealed class LocalizationService
{
    public const string LanguageSystem = SettingsService.LanguageSystem;
    public const string LanguageChinese = SettingsService.LanguageChinese;
    public const string LanguageEnglish = SettingsService.LanguageEnglish;

    private readonly SettingsService _settingsService;

    public event Action? LanguageChanged;

    public LocalizationService(SettingsService settingsService)
    {
        _settingsService = settingsService;
    }

    public string LanguageSetting => NormalizeLanguageSetting(_settingsService.Settings.Language);

    public string CurrentCultureName
    {
        get
        {
            string language = LanguageSetting;
            if (language == LanguageSystem)
            {
                language = ResolveSystemLanguage();
            }

            return language;
        }
    }

    public bool IsEnglish => string.Equals(CurrentCultureName, LanguageEnglish, StringComparison.OrdinalIgnoreCase);

    public IReadOnlyList<string> AvailableLanguageSettings { get; } =
    [
        LanguageSystem,
        LanguageChinese,
        LanguageEnglish
    ];

    public string GetLanguageDisplayName(string language)
    {
        return NormalizeLanguageSetting(language) switch
        {
            LanguageChinese => T("Language.Chinese"),
            LanguageEnglish => T("Language.English"),
            _ => T("Language.System")
        };
    }

    public void SetLanguage(string language)
    {
        string normalizedLanguage = NormalizeLanguageSetting(language);
        if (string.Equals(_settingsService.Settings.Language, normalizedLanguage, StringComparison.Ordinal))
        {
            return;
        }

        _settingsService.Settings.Language = normalizedLanguage;
        _settingsService.SaveDebounced();
        LanguageChanged?.Invoke();
    }

    public string T(string key)
    {
        var table = IsEnglish ? EnUs : ZhCn;
        if (table.TryGetValue(key, out string? value))
        {
            return value;
        }

        return ZhCn.TryGetValue(key, out value) ? value : key;
    }

    public string Format(string key, params object[] args)
    {
        return string.Format(CultureInfo.CurrentCulture, T(key), args);
    }

    public static string DefaultText(string key)
    {
        return ZhCn.TryGetValue(key, out string? value) ? value : key;
    }

    public static string DefaultFormat(string key, params object[] args)
    {
        return string.Format(CultureInfo.CurrentCulture, DefaultText(key), args);
    }

    public static string NormalizeLanguageSetting(string? language)
    {
        return language is LanguageChinese or LanguageEnglish
            ? language
            : LanguageSystem;
    }

    private static string ResolveSystemLanguage()
    {
        string name = CultureInfo.CurrentUICulture.Name;
        return name.StartsWith("zh", StringComparison.OrdinalIgnoreCase)
            ? LanguageChinese
            : LanguageEnglish;
    }

    private static readonly Dictionary<string, string> ZhCn = new()
    {
        ["Common.Ok"] = "确定",
        ["Common.Cancel"] = "取消",
        ["Common.Continue"] = "继续",
        ["Common.Open"] = "打开",
        ["Common.Change"] = "更改",
        ["Common.Cleanup"] = "清理",
        ["Common.View"] = "查看",
        ["Common.Restore"] = "恢复",
        ["Common.Copy"] = "复制",
        ["Common.Cut"] = "剪切",
        ["Common.Move"] = "移动",
        ["Common.Delete"] = "删除",
        ["Common.Rename"] = "重命名",
        ["Common.Properties"] = "属性",
        ["Common.Refresh"] = "刷新",
        ["Common.Paste"] = "粘贴",
        ["Common.NewFolder"] = "新建文件夹",
        ["Common.NewWidget"] = "新建组件",
        ["Common.NewFolderMapping"] = "新建文件夹映射",
        ["Common.Desktop"] = "桌面",
        ["Common.CurrentLocation"] = "当前位置",
        ["Common.Items"] = "项",
        ["Common.Failed"] = "失败",
        ["Common.Undone"] = "已撤销",
        ["Common.On"] = "开启",
        ["Common.Off"] = "关闭",

        ["Language.System"] = "跟随系统",
        ["Language.Chinese"] = "中文",
        ["Language.English"] = "English",

        ["Settings.WindowTitle"] = "DeskBox 设置",
        ["Settings.Title"] = "设置",
        ["Settings.Section.Appearance"] = "外观",
        ["Settings.Theme.Title"] = "应用主题",
        ["Settings.Theme.Description"] = "跟随系统，或固定浅色/深色",
        ["Settings.Theme.System"] = "跟随系统",
        ["Settings.Theme.Light"] = "浅色",
        ["Settings.Theme.Dark"] = "深色",
        ["Settings.Language.Title"] = "语言",
        ["Settings.Language.Description"] = "切换 DeskBox 的界面语言",
        ["Settings.SystemAccent.Title"] = "使用 Windows 主题色",
        ["Settings.SystemAccent.Description"] = "开启后使用 Windows 当前强调色",
        ["Settings.Accent.Title"] = "主题色",
        ["Settings.Accent.SystemDescription"] = "使用 Windows 当前的主题色",
        ["Settings.Accent.CustomDescription"] = "点击右侧颜色按钮，或使用预设颜色",
        ["Settings.Accent.Tooltip"] = "选择自定义主题色",
        ["Settings.Section.WidgetDefaults"] = "组件默认值",
        ["Settings.DefaultWidth.Title"] = "默认宽度",
        ["Settings.DefaultWidth.Description"] = "新建组件时使用，单位为像素",
        ["Settings.DefaultHeight.Title"] = "默认高度",
        ["Settings.DefaultHeight.Description"] = "新建组件时使用，单位为像素",
        ["Settings.Section.DisplayDensity"] = "显示密度",
        ["Settings.Corner.Title"] = "组件圆角",
        ["Settings.Corner.Description"] = "控制桌面组件窗口的原生 DWM 圆角",
        ["Settings.Corner.Default"] = "系统默认",
        ["Settings.Corner.Square"] = "直角",
        ["Settings.Corner.Small"] = "小圆角",
        ["Settings.Corner.Round"] = "大圆角",
        ["Settings.Animation.Effect.Title"] = "显示动画",
        ["Settings.Animation.Effect.Description"] = "调整桌面格子出现和隐藏的动效",
        ["Settings.Animation.Effect.None"] = "无动画",
        ["Settings.Animation.Effect.Fade"] = "淡入淡出",
        ["Settings.Animation.Effect.SlideRight"] = "从右侧滑入",
        ["Settings.Animation.Effect.SlideLeft"] = "从左侧滑入",
        ["Settings.Animation.Effect.SlideUp"] = "从上方滑入",
        ["Settings.Animation.Effect.SlideDown"] = "从下方滑入",
        ["Settings.Animation.Effect.ScaleFade"] = "缩放淡入",
        ["Settings.Animation.Effect.SlideFade"] = "滑动淡入",
        ["Settings.Animation.Speed.Title"] = "动画速度",
        ["Settings.Animation.Speed.Description"] = "选择格子动画的持续时长",
        ["Settings.Animation.Speed.VeryFast"] = "极快",
        ["Settings.Animation.Speed.Fast"] = "快速",
        ["Settings.Animation.Speed.Standard"] = "标准",
        ["Settings.Animation.Speed.Relaxed"] = "舒缓",
        ["Settings.Animation.Speed.Slow"] = "慢速",
        ["Settings.Opacity.Title"] = "背景透明度",
        ["Settings.IconSize.Title"] = "图标大小",
        ["Settings.TextSize.Title"] = "文字大小",
        ["Settings.HorizontalSpacing.Title"] = "横向间距",
        ["Settings.VerticalSpacing.Title"] = "纵向间距",
        ["Settings.FileNameWidth.Title"] = "文件名宽度",
        ["Settings.Section.Storage"] = "收纳",
        ["Settings.DropAction.Title"] = "拖入后的处理方式",
        ["Settings.DropAction.Description"] = "移动用于整理桌面，复制会保留原文件",
        ["Settings.DropAction.Move"] = "移动",
        ["Settings.DropAction.Copy"] = "复制",
        ["Settings.ManagedPath.Title"] = "默认收纳路径",
        ["Settings.ManagedPath.Description"] = "新建收纳组件会在这里创建独立文件夹",
        ["Settings.ManagedPath.OpenTooltip"] = "在文件资源管理器中打开默认收纳路径",
        ["Settings.ManagedPath.ChangeTooltip"] = "选择新的默认收纳路径",
        ["Settings.ManagedPath.CleanupTooltip"] = "清理不再属于现有组件的收纳文件夹",
        ["Settings.Section.Interaction"] = "交互",
        ["Settings.DoubleClick.Title"] = "双击打开项目",
        ["Settings.DoubleClick.Description"] = "关闭后单击即可打开",
        ["Settings.HideShortcutArrow.Title"] = "隐藏快捷方式小箭头",
        ["Settings.HideShortcutArrow.Description"] = "只影响 DeskBox 组件内的图标显示",
        ["Settings.ListDetails.Title"] = "列表详细信息",
        ["Settings.ListDetails.Description"] = "列表模式下显示大小、时间或文件夹项目数量",
        ["Settings.Section.System"] = "系统",
        ["Settings.AutoStart.Title"] = "开机自动启动",
        ["Settings.AutoStart.Description"] = "登录 Windows 后在后台启动 DeskBox",
        ["Settings.Onboarding.Title"] = "新手引导",
        ["Settings.Onboarding.Description"] = "重新查看收纳、映射、文件安全和托盘操作说明",
        ["Settings.Onboarding.Tooltip"] = "打开 DeskBox 新手引导",
        ["Settings.Restore.Title"] = "恢复默认设置",
        ["Settings.Restore.Description"] = "恢复外观、显示和交互偏好，不会修改开机自启和收纳路径",
        ["Settings.Restore.Tooltip"] = "恢复 DeskBox 默认偏好",
        ["Settings.Section.About"] = "关于",
        ["Settings.About.Description"] = "桌面收纳与整理工具",
        ["Settings.About.ReasonTitle"] = "为什么做 DeskBox",
        ["Settings.About.ReasonButton"] = "初衷",
        ["Settings.About.Repository"] = "开源仓库",
        ["Settings.About.RepositoryDescription"] = "查看项目代码、反馈问题或参与改进",
        ["Settings.About.Version"] = "版本 {0} · WinUI 3 / .NET 8",
        ["Settings.About.Developer"] = "开发者：朱天雨 · GitHub：{0}",
        ["Settings.Dialog.AccentTitle"] = "自定义主题色",
        ["Settings.Dialog.MigrateTitle"] = "迁移默认收纳路径",
        ["Settings.Dialog.MigrateButton"] = "迁移",
        ["Settings.Dialog.MigrateBody"] = "将把 {0} 个跟随默认路径的收纳组件从\n{1}\n迁移到\n{2}\n\n文件夹映射组件不会受到影响。",
        ["Settings.Dialog.MigrateFailedTitle"] = "迁移失败",
        ["Settings.Dialog.MigrateFailedBody"] = "默认收纳路径没有更新。\n\n{0}",
        ["Settings.Dialog.RestoreTitle"] = "恢复默认设置",
        ["Settings.Dialog.RestoreBody"] = "将恢复外观、显示、交互和整理偏好。开机自启、默认收纳路径、已有组件和文件不会被修改。",
        ["Settings.Dialog.ProductReasonP1"] = "很多桌面管理工具会接管桌面，替换原来的桌面交互，甚至把桌面变成另一套文件入口。DeskBox 不想这么做。",
        ["Settings.Dialog.ProductReasonP2"] = "它更像是一层轻量整理能力：桌面仍然是桌面，文件仍然是普通文件，组件只负责把文件移动、复制或映射到合适的位置。",
        ["Settings.Dialog.ProductReasonP3"] = "界面上，DeskBox 尽量围绕 WinUI 3、Windows App SDK、Mica 和 DWM 圆角构建，目标是在保留 Windows 原生质感的同时，把桌面整理这件事变得更顺手。",
        ["Settings.Dialog.ProductReasonClose"] = "知道了",
        ["Settings.Dialog.CleanupTitle"] = "清理孤立收纳文件夹",
        ["Settings.Dialog.CleanupNone"] = "没有发现孤立的收纳文件夹。",
        ["Settings.Dialog.CleanupOptionOpen"] = "打开默认收纳路径，稍后自行处理",
        ["Settings.Dialog.CleanupOptionMove"] = "把这些文件夹的内容移回桌面，然后删除空文件夹",
        ["Settings.Dialog.CleanupOptionDelete"] = "把这些孤立文件夹移到回收站",
        ["Settings.Dialog.CleanupBody"] = "发现 {0} 个不再属于现有组件的收纳文件夹。请选择处理方式：",
        ["Settings.Dialog.CleanupComplete"] = "清理完成",
        ["Settings.Dialog.CleanupMoved"] = "孤立收纳文件夹的内容已移回桌面。",
        ["Settings.Dialog.CleanupDeleted"] = "孤立收纳文件夹已移到回收站。",
        ["Settings.Dialog.CleanupFailed"] = "清理失败",
        ["Settings.Dialog.CleanupFailedBody"] = "收纳文件夹没有完全清理。\n\n{0}",
        ["Settings.Cleanup.MoreFolders"] = "还有 {0} 个文件夹未显示。",
        ["Settings.Cleanup.ItemCount"] = "项",

        ["Onboarding.WindowTitle"] = "DeskBox 新手引导",
        ["Onboarding.Skip"] = "跳过",
        ["Onboarding.Back"] = "上一步",
        ["Onboarding.Next"] = "下一步",
        ["Onboarding.Start"] = "开始使用",
        ["Onboarding.Step1.Eyebrow"] = "基础",
        ["Onboarding.Step1.Title"] = "格子不替代桌面",
        ["Onboarding.Step1.Body"] = "DeskBox 只在 Windows 桌面上叠一层格子：收纳文件，或映射文件夹。",
        ["Onboarding.Step1.Hint1"] = "桌面文件仍由 Windows 管理",
        ["Onboarding.Step1.Hint2"] = "格子用于整理、查看和快速访问",
        ["Onboarding.Step1.Widget"] = "我的桌面",
        ["Onboarding.Step2.Eyebrow"] = "拖入文件",
        ["Onboarding.Step2.Title"] = "拖入后怎么处理？",
        ["Onboarding.Step2.Body"] = "收纳格子会把文件放进默认收纳路径。你可以选择移动或复制。",
        ["Onboarding.Step2.Hint1"] = "移动：原位置消失，桌面更干净",
        ["Onboarding.Step2.Hint2"] = "复制：原文件保留，格子里放副本",
        ["Onboarding.Step2.Widget"] = "拖入行为",
        ["Onboarding.Step3.Eyebrow"] = "收纳路径",
        ["Onboarding.Step3.Title"] = "文件实际放这里",
        ["Onboarding.Step3.Body"] = "拖进收纳格子的文件，会保存到这个默认路径。现在可以确认或更改。",
        ["Onboarding.Step3.Hint1"] = "以后仍可在设置里修改",
        ["Onboarding.Step3.Hint2"] = "已有收纳格子会提示是否迁移",
        ["Onboarding.Step3.Widget"] = "默认路径",
        ["Onboarding.Step4.Eyebrow"] = "文件夹映射",
        ["Onboarding.Step4.Title"] = "映射只查看文件夹",
        ["Onboarding.Step4.Body"] = "映射格子显示一个真实文件夹，文件不搬进 DeskBox。",
        ["Onboarding.Step4.Hint1"] = "适合项目、素材、下载目录",
        ["Onboarding.Step4.Hint2"] = "映射路径可以随时更改",
        ["Onboarding.Step4.Widget"] = "文件夹映射",
        ["Onboarding.Step5.Eyebrow"] = "完成",
        ["Onboarding.Step5.Title"] = "最后一步",
        ["Onboarding.Step5.Body"] = "开启后，DeskBox 登录 Windows 后静默启动，托盘和格子会自动可用。",
        ["Onboarding.Step5.Hint1"] = "托盘可显示、隐藏和管理格子",
        ["Onboarding.Step5.Hint2"] = "设置里可重新打开引导",
        ["Onboarding.Step5.Widget"] = "开始使用",
        ["Onboarding.Welcome.ManagedTitle"] = "收纳格子",
        ["Onboarding.Welcome.ManagedDescription"] = "拖入后按选择移动或复制。",
        ["Onboarding.Welcome.MappedTitle"] = "映射格子",
        ["Onboarding.Welcome.MappedDescription"] = "只显示真实文件夹，不搬文件。",
        ["Onboarding.DropAction.MoveTitle"] = "移动",
        ["Onboarding.DropAction.MoveDescription"] = "原位置消失，文件进入收纳路径。",
        ["Onboarding.DropAction.CopyTitle"] = "复制",
        ["Onboarding.DropAction.CopyDescription"] = "保留原文件，格子里放副本。",
        ["Onboarding.Storage.CurrentPath"] = "默认收纳路径",
        ["Onboarding.Storage.ChangePath"] = "更改路径",
        ["Onboarding.Mapping.ManagedTitle"] = "收纳格子",
        ["Onboarding.Mapping.ManagedDescription"] = "管理拖入的文件，存到收纳路径。",
        ["Onboarding.Mapping.MappedTitle"] = "映射格子",
        ["Onboarding.Mapping.MappedDescription"] = "查看真实文件夹，文件留在原处。",
        ["Onboarding.Startup.Title"] = "开机自动启动",
        ["Onboarding.Startup.Description"] = "登录后静默启动，托盘可用。",
        ["Onboarding.Scene.Desktop"] = "Windows 桌面",
        ["Onboarding.Scene.DesktopFile"] = "桌面文件",
        ["Onboarding.Scene.ProjectFolder"] = "项目文件夹",
        ["Onboarding.Scene.ManagedWidget"] = "收纳格子",
        ["Onboarding.Scene.MappedWidget"] = "映射格子",
        ["Onboarding.Scene.DefaultStorage"] = "收纳路径",
        ["Onboarding.Scene.OriginalFolder"] = "真实文件夹",
        ["Onboarding.Scene.NativeDesktop"] = "桌面仍原生",
        ["Onboarding.Scene.MoveBadge"] = "移动",
        ["Onboarding.Scene.CopyBadge"] = "复制",
        ["Onboarding.Scene.ViewOnly"] = "只查看",
        ["Onboarding.Scene.Startup"] = "后台启动",
        ["Onboarding.Scene.StartupOff"] = "手动启动",

        ["Tray.Tooltip"] = "DeskBox 桌面收纳",
        ["Tray.TooltipRaised"] = "DeskBox 桌面收纳 - 组件已临时置顶",
        ["Tray.TooltipNormal"] = "DeskBox 桌面收纳 - 左键单击置顶组件",
        ["Tray.ShowAll"] = "显示全部组件",
        ["Tray.HideAll"] = "隐藏全部组件",
        ["Tray.Settings"] = "设置",
        ["Tray.AutoStart"] = "开机启动",
        ["Tray.Exit"] = "退出",
        ["Widget.DefaultName"] = "新建收纳组件",
        ["Widget.DefaultNameShort"] = "新建组件",
        ["Widget.DefaultDesktopName"] = "我的桌面",
        ["Widget.ManagedFolderBaseName"] = "收纳组件",
        ["Widget.NewFolderName"] = "新建文件夹",
        ["Widget.Mode.Managed"] = "收纳",
        ["Widget.Mode.Mapped"] = "映射",
        ["Widget.ModeInfo"] = "组件类型：{0}组件",
        ["Widget.Mode.ManagedDescription"] = "收纳组件，拖入文件会自动整理到默认收纳路径。",
        ["Widget.Mode.MappedDescription"] = "文件夹映射组件，直接展示指定文件夹内容。",
        ["Widget.Empty.ManagedTitle"] = "还没有收纳内容",
        ["Widget.Empty.MappedTitle"] = "文件夹里暂无文件",
        ["Widget.Empty.ManagedText"] = "把文件拖到这里，DeskBox 会自动{0}到 {1}。",
        ["Widget.Empty.MappedText"] = "这里会同步显示 {0} 中的内容。",
        ["Widget.DragCaption.CurrentWidget"] = "已在当前组件中",
        ["Widget.DragCaption.Managed"] = "{0}到收纳组件",
        ["Widget.DragCaption.Reference"] = "添加到引用组件",
        ["Widget.Tooltip.Add"] = "新建",
        ["Widget.Tooltip.More"] = "更多选项",
        ["Widget.Tooltip.DeleteWidget"] = "删除组件",
        ["Widget.TitlePlaceholder"] = "输入组件名称",
        ["Widget.AddFile"] = "添加文件",
        ["Widget.ChangeMappedPath"] = "更改映射路径",
        ["Widget.IconView"] = "图标视图",
        ["Widget.ListView"] = "列表视图",
        ["Widget.LockPosition"] = "锁定位置",
        ["Widget.LockSize"] = "锁定尺寸",
        ["Widget.OpenCurrentFolder"] = "打开当前文件夹",
        ["Widget.Open"] = "打开",
        ["Widget.ShowInExplorer"] = "在文件资源管理器中显示",
        ["Widget.ItemCount"] = "{0} 个项目",
        ["Widget.CopyPathCount"] = "已复制路径 {0} 项",
        ["Widget.SelectedCount"] = "已选择 {0} 项",
        ["Widget.MoveBackToDesktop"] = "移回桌面",
        ["Widget.MoveToDesktop"] = "移到桌面",
        ["Widget.MoveBackToDesktopFailed"] = "移回桌面失败",
        ["Widget.MoveToDesktopFailed"] = "移到桌面失败",
        ["Widget.NoItemsMoved"] = "没有项目被移动",
        ["Widget.CannotMoveToFolder"] = "不能移动到此文件夹",
        ["Widget.CopyToFolder"] = "复制到“{0}”",
        ["Widget.MoveToFolder"] = "移动到“{0}”",
        ["Widget.CopiedToFolder"] = "已复制到 {0} {1} 项",
        ["Widget.MovedToFolder"] = "已移动到 {0} {1} 项",
        ["Widget.MoveToFolderFailed"] = "移动到文件夹失败",
        ["Widget.AddedFile"] = "已添加文件",
        ["Widget.AddedFiles"] = "已添加 {0} 个文件",
        ["Widget.AddFileFailed"] = "添加文件失败",
        ["Widget.MappedPathUpdated"] = "映射路径已更新",
        ["Widget.ChangeMappedPathFailed"] = "更改映射路径失败",
        ["Widget.CreateFolderFailed"] = "新建文件夹失败",
        ["Widget.DeleteFailed"] = "删除失败",
        ["Widget.RenameFailed"] = "重命名失败",
        ["Widget.DeleteWidgetFailed"] = "删除组件失败",
        ["Widget.PasteFailed"] = "粘贴失败",
        ["Widget.RefreshFailed"] = "刷新失败",
        ["Widget.NoCopyableItems"] = "没有可复制的项目",
        ["Widget.CutCount"] = "已剪切 {0} 项",
        ["Widget.CopyCount"] = "已复制 {0} 项",
        ["Widget.MovedCount"] = "已移动 {0} 项",
        ["Widget.PastedCount"] = "已粘贴 {0} 项",
        ["Widget.Refreshed"] = "已刷新",
        ["Widget.DeleteItemsTitleOne"] = "将“{0}”移到回收站？",
        ["Widget.DeleteItemsTitleMany"] = "将 {0} 项移到回收站？",
        ["Widget.DeleteFolderNoteOne"] = "这是文件夹，里面的内容也会一起进入回收站",
        ["Widget.DeleteFolderNoteMany"] = "其中包含 {0} 个文件夹，文件夹内容也会一起进入回收站",
        ["Widget.MoveToRecycleBin"] = "移到回收站",
        ["Widget.MovedToRecycleBin"] = "已移到回收站 {0} 项",
        ["Widget.MovedBackToDesktop"] = "已移回桌面 {0} 项",
        ["Widget.MovedToDesktop"] = "已移到桌面 {0} 项",
        ["Widget.DeleteWidgetTitle"] = "删除“{0}”",
        ["Widget.DeleteWidgetNote"] = "只移除组件，不删除原文件",
        ["Widget.DeleteWidgetConfirm"] = "确认删除组件",
        ["Widget.DeleteManagedInfo"] = "选择收纳文件夹处理方式",
        ["Widget.KeepManagedFolder"] = "保留收纳文件夹",
        ["Widget.MoveBackThenDeleteFolder"] = "移回桌面后删除空文件夹",
        ["Widget.DeleteFolderToRecycleBin"] = "删除文件夹，文件进回收站",
        ["Widget.Error.OperationIncomplete"] = "操作没有完成。",
        ["Widget.Error.OperationCanceled"] = "操作已取消。",
        ["Widget.Error.AccessDenied"] = "没有权限完成这个操作。\n\n{0}",
        ["Widget.Error.FileInUse"] = "文件正在被其他程序使用，请关闭相关程序后再试。",
        ["Widget.Error.FileInUseWithPath"] = "文件正在被其他程序使用，请关闭相关程序后再试。\n\n{0}",
        ["Widget.Error.DuplicateName"] = "目标位置已经有同名项目。\n\n{0}",
        ["Widget.Validation.NameRequired"] = "名称不能为空。",
        ["Widget.Validation.FolderUnknown"] = "无法确定当前项目所在的文件夹。",
        ["Widget.Validation.TargetExists"] = "目标名称已存在。",
        ["Widget.Error.ClipboardAllocate"] = "无法分配剪贴板数据。",
        ["Widget.Error.ClipboardWrite"] = "无法写入剪贴板数据。",
        ["Widget.Error.ManagedFolderCleanupOnlyDefault"] = "只能清理默认收纳路径下的直属文件夹。",
        ["Widget.Error.ManagedFolderStillActive"] = "这个文件夹仍然属于现有收纳组件，不能作为孤立文件夹清理。",
        ["Widget.Error.ManagedFolderActionOnlyDefault"] = "只有默认收纳路径下的收纳组件可以同步处理文件夹。",
        ["History.Title.CopyToManaged"] = "复制到收纳组件",
        ["History.Title.MoveToManaged"] = "移动到收纳组件",
        ["History.Title.MoveBackToDesktop"] = "移回桌面",
        ["History.Title.DesktopOrganization"] = "桌面整理",
        ["History.CurrentWidget"] = "当前组件",
        ["History.NoItems"] = "没有记录到项目。",
        ["History.ItemSummary"] = "{0} 等 {1} 项",
        ["History.UndoMoveBackToDesktop"] = "撤销移回桌面",
        ["History.UndoLastMove"] = "撤销上次移动",
        ["History.OperationFailed"] = "操作失败",
        ["FileInfo.File"] = "文件",
        ["FileInfo.FolderItems"] = "{0} 项",
        ["FileInfo.FileModified"] = "{0} · {1:yyyy/M/d HH:mm}"
    };

    private static readonly Dictionary<string, string> EnUs = new()
    {
        ["Common.Ok"] = "OK",
        ["Common.Cancel"] = "Cancel",
        ["Common.Continue"] = "Continue",
        ["Common.Open"] = "Open",
        ["Common.Change"] = "Change",
        ["Common.Cleanup"] = "Clean Up",
        ["Common.View"] = "View",
        ["Common.Restore"] = "Restore",
        ["Common.Copy"] = "Copy",
        ["Common.Cut"] = "Cut",
        ["Common.Move"] = "Move",
        ["Common.Delete"] = "Delete",
        ["Common.Rename"] = "Rename",
        ["Common.Properties"] = "Properties",
        ["Common.Refresh"] = "Refresh",
        ["Common.Paste"] = "Paste",
        ["Common.NewFolder"] = "New Folder",
        ["Common.NewWidget"] = "New Widget",
        ["Common.NewFolderMapping"] = "New Folder Mapping",
        ["Common.Desktop"] = "Desktop",
        ["Common.CurrentLocation"] = "Current location",
        ["Common.Items"] = "items",
        ["Common.Failed"] = "Failed",
        ["Common.Undone"] = "Undone",
        ["Common.On"] = "On",
        ["Common.Off"] = "Off",

        ["Language.System"] = "Use system language",
        ["Language.Chinese"] = "中文",
        ["Language.English"] = "English",

        ["Settings.WindowTitle"] = "DeskBox Settings",
        ["Settings.Title"] = "Settings",
        ["Settings.Section.Appearance"] = "Appearance",
        ["Settings.Theme.Title"] = "App theme",
        ["Settings.Theme.Description"] = "Follow Windows, or use light/dark mode",
        ["Settings.Theme.System"] = "Use system setting",
        ["Settings.Theme.Light"] = "Light",
        ["Settings.Theme.Dark"] = "Dark",
        ["Settings.Language.Title"] = "Language",
        ["Settings.Language.Description"] = "Change the DeskBox interface language",
        ["Settings.SystemAccent.Title"] = "Use Windows accent color",
        ["Settings.SystemAccent.Description"] = "Use the current Windows accent color",
        ["Settings.Accent.Title"] = "Accent color",
        ["Settings.Accent.SystemDescription"] = "Using the current Windows accent color",
        ["Settings.Accent.CustomDescription"] = "Use the color button or choose a preset",
        ["Settings.Accent.Tooltip"] = "Choose a custom accent color",
        ["Settings.Section.WidgetDefaults"] = "Widget Defaults",
        ["Settings.DefaultWidth.Title"] = "Default width",
        ["Settings.DefaultWidth.Description"] = "Used for new widgets, in pixels",
        ["Settings.DefaultHeight.Title"] = "Default height",
        ["Settings.DefaultHeight.Description"] = "Used for new widgets, in pixels",
        ["Settings.Section.DisplayDensity"] = "Display Density",
        ["Settings.Corner.Title"] = "Widget corners",
        ["Settings.Corner.Description"] = "Controls the native DWM corner style for desktop widgets",
        ["Settings.Corner.Default"] = "System default",
        ["Settings.Corner.Square"] = "Square",
        ["Settings.Corner.Small"] = "Small radius",
        ["Settings.Corner.Round"] = "Large radius",
        ["Settings.Animation.Effect.Title"] = "Widget animation",
        ["Settings.Animation.Effect.Description"] = "Adjust how desktop widgets show and hide",
        ["Settings.Animation.Effect.None"] = "None",
        ["Settings.Animation.Effect.Fade"] = "Fade",
        ["Settings.Animation.Effect.SlideRight"] = "Slide from right",
        ["Settings.Animation.Effect.SlideLeft"] = "Slide from left",
        ["Settings.Animation.Effect.SlideUp"] = "Slide from top",
        ["Settings.Animation.Effect.SlideDown"] = "Slide from bottom",
        ["Settings.Animation.Effect.ScaleFade"] = "Scale fade",
        ["Settings.Animation.Effect.SlideFade"] = "Slide fade",
        ["Settings.Animation.Speed.Title"] = "Animation speed",
        ["Settings.Animation.Speed.Description"] = "Choose how long widget animations last",
        ["Settings.Animation.Speed.VeryFast"] = "Very fast",
        ["Settings.Animation.Speed.Fast"] = "Fast",
        ["Settings.Animation.Speed.Standard"] = "Standard",
        ["Settings.Animation.Speed.Relaxed"] = "Relaxed",
        ["Settings.Animation.Speed.Slow"] = "Slow",
        ["Settings.Opacity.Title"] = "Background opacity",
        ["Settings.IconSize.Title"] = "Icon size",
        ["Settings.TextSize.Title"] = "Text size",
        ["Settings.HorizontalSpacing.Title"] = "Horizontal spacing",
        ["Settings.VerticalSpacing.Title"] = "Vertical spacing",
        ["Settings.FileNameWidth.Title"] = "File name width",
        ["Settings.Section.Storage"] = "Storage",
        ["Settings.DropAction.Title"] = "Drop behavior",
        ["Settings.DropAction.Description"] = "Move organizes the desktop; Copy keeps the original files",
        ["Settings.DropAction.Move"] = "Move",
        ["Settings.DropAction.Copy"] = "Copy",
        ["Settings.ManagedPath.Title"] = "Default storage path",
        ["Settings.ManagedPath.Description"] = "New managed widgets create separate folders here",
        ["Settings.ManagedPath.OpenTooltip"] = "Open the default storage path in File Explorer",
        ["Settings.ManagedPath.ChangeTooltip"] = "Choose a new default storage path",
        ["Settings.ManagedPath.CleanupTooltip"] = "Clean up storage folders no longer used by widgets",
        ["Settings.Section.Interaction"] = "Interaction",
        ["Settings.DoubleClick.Title"] = "Double-click to open items",
        ["Settings.DoubleClick.Description"] = "When off, single-click opens items",
        ["Settings.HideShortcutArrow.Title"] = "Hide shortcut arrow overlay",
        ["Settings.HideShortcutArrow.Description"] = "Only affects icons shown inside DeskBox widgets",
        ["Settings.ListDetails.Title"] = "List details",
        ["Settings.ListDetails.Description"] = "Show size, time, or folder item count in list view",
        ["Settings.Section.System"] = "System",
        ["Settings.AutoStart.Title"] = "Launch at startup",
        ["Settings.AutoStart.Description"] = "Start DeskBox in the background after Windows sign-in",
        ["Settings.Onboarding.Title"] = "Onboarding",
        ["Settings.Onboarding.Description"] = "Review storage, mapping, file safety, and tray behavior",
        ["Settings.Onboarding.Tooltip"] = "Open DeskBox onboarding",
        ["Settings.Restore.Title"] = "Restore defaults",
        ["Settings.Restore.Description"] = "Restore appearance, display, and interaction preferences without changing startup or storage paths",
        ["Settings.Restore.Tooltip"] = "Restore default DeskBox preferences",
        ["Settings.Section.About"] = "About",
        ["Settings.About.Description"] = "Desktop storage and organization tool",
        ["Settings.About.ReasonTitle"] = "Why DeskBox",
        ["Settings.About.ReasonButton"] = "Why",
        ["Settings.About.Repository"] = "Open-source repository",
        ["Settings.About.RepositoryDescription"] = "View code, report issues, or contribute improvements",
        ["Settings.About.Version"] = "Version {0} · WinUI 3 / .NET 8",
        ["Settings.About.Developer"] = "Developer: Zhu Tianyu · GitHub: {0}",
        ["Settings.Dialog.AccentTitle"] = "Custom Accent Color",
        ["Settings.Dialog.MigrateTitle"] = "Move Default Storage Path",
        ["Settings.Dialog.MigrateButton"] = "Move",
        ["Settings.Dialog.MigrateBody"] = "{0} managed widget(s) that follow the default path will move from\n{1}\nto\n{2}\n\nFolder-mapping widgets will not be affected.",
        ["Settings.Dialog.MigrateFailedTitle"] = "Move Failed",
        ["Settings.Dialog.MigrateFailedBody"] = "The default storage path was not updated.\n\n{0}",
        ["Settings.Dialog.RestoreTitle"] = "Restore Defaults",
        ["Settings.Dialog.RestoreBody"] = "Appearance, display, interaction, and organization preferences will be restored. Startup, default storage path, existing widgets, and files will not be changed.",
        ["Settings.Dialog.ProductReasonP1"] = "Many desktop management tools take over the desktop, replace its normal interactions, or turn it into another file launcher. DeskBox avoids that.",
        ["Settings.Dialog.ProductReasonP2"] = "It is a lightweight organization layer: the desktop stays the desktop, files remain ordinary files, and widgets only move, copy, or map files into useful places.",
        ["Settings.Dialog.ProductReasonP3"] = "Visually, DeskBox follows WinUI 3, Windows App SDK, Mica, and DWM corners so desktop organization feels native and easier to use.",
        ["Settings.Dialog.ProductReasonClose"] = "Got it",
        ["Settings.Dialog.CleanupTitle"] = "Clean Up Orphan Storage Folders",
        ["Settings.Dialog.CleanupNone"] = "No orphan storage folders were found.",
        ["Settings.Dialog.CleanupOptionOpen"] = "Open the default storage path and handle them later",
        ["Settings.Dialog.CleanupOptionMove"] = "Move these folder contents back to Desktop, then delete empty folders",
        ["Settings.Dialog.CleanupOptionDelete"] = "Move these orphan folders to Recycle Bin",
        ["Settings.Dialog.CleanupBody"] = "{0} storage folder(s) no longer belong to existing widgets. Choose how to handle them:",
        ["Settings.Dialog.CleanupComplete"] = "Cleanup Complete",
        ["Settings.Dialog.CleanupMoved"] = "The orphan storage folder contents were moved back to Desktop.",
        ["Settings.Dialog.CleanupDeleted"] = "The orphan storage folders were moved to Recycle Bin.",
        ["Settings.Dialog.CleanupFailed"] = "Cleanup Failed",
        ["Settings.Dialog.CleanupFailedBody"] = "The storage folders were not fully cleaned up.\n\n{0}",
        ["Settings.Cleanup.MoreFolders"] = "{0} more folder(s) are not shown.",
        ["Settings.Cleanup.ItemCount"] = "items",

        ["Onboarding.WindowTitle"] = "DeskBox Onboarding",
        ["Onboarding.Skip"] = "Skip",
        ["Onboarding.Back"] = "Back",
        ["Onboarding.Next"] = "Next",
        ["Onboarding.Start"] = "Get Started",
        ["Onboarding.Step1.Eyebrow"] = "Basics",
        ["Onboarding.Step1.Title"] = "Widgets stay above Desktop",
        ["Onboarding.Step1.Body"] = "DeskBox adds lightweight widgets on top of Windows Desktop: store files or map folders.",
        ["Onboarding.Step1.Hint1"] = "Windows still manages Desktop files",
        ["Onboarding.Step1.Hint2"] = "Widgets organize, preview, and open files fast",
        ["Onboarding.Step1.Widget"] = "My Desktop",
        ["Onboarding.Step2.Eyebrow"] = "Dropping files",
        ["Onboarding.Step2.Title"] = "Move or copy on drop?",
        ["Onboarding.Step2.Body"] = "Managed widgets place dropped files in the default storage path.",
        ["Onboarding.Step2.Hint1"] = "Move: remove the original and clean Desktop",
        ["Onboarding.Step2.Hint2"] = "Copy: keep the original and add a copy",
        ["Onboarding.Step2.Widget"] = "Drop behavior",
        ["Onboarding.Step3.Eyebrow"] = "Storage path",
        ["Onboarding.Step3.Title"] = "Files live here",
        ["Onboarding.Step3.Body"] = "Files dropped into managed widgets are stored in this default path. Review or change it now.",
        ["Onboarding.Step3.Hint1"] = "You can change it later in Settings",
        ["Onboarding.Step3.Hint2"] = "Existing widgets will ask before migration",
        ["Onboarding.Step3.Widget"] = "Default path",
        ["Onboarding.Step4.Eyebrow"] = "Folder mapping",
        ["Onboarding.Step4.Title"] = "Mapping only views folders",
        ["Onboarding.Step4.Body"] = "Mapped widgets show a real folder. Files stay where they already are.",
        ["Onboarding.Step4.Hint1"] = "Good for projects, assets, and Downloads",
        ["Onboarding.Step4.Hint2"] = "You can change the mapped path anytime",
        ["Onboarding.Step4.Widget"] = "Folder mapping",
        ["Onboarding.Step5.Eyebrow"] = "Finish",
        ["Onboarding.Step5.Title"] = "One last choice",
        ["Onboarding.Step5.Body"] = "When enabled, DeskBox starts quietly after Windows sign-in so tray controls and widgets are ready.",
        ["Onboarding.Step5.Hint1"] = "Use the tray to show, hide, and manage widgets",
        ["Onboarding.Step5.Hint2"] = "You can reopen this guide from Settings",
        ["Onboarding.Step5.Widget"] = "Get started",
        ["Onboarding.Welcome.ManagedTitle"] = "Managed widget",
        ["Onboarding.Welcome.ManagedDescription"] = "Move or copy files when dropped.",
        ["Onboarding.Welcome.MappedTitle"] = "Mapped widget",
        ["Onboarding.Welcome.MappedDescription"] = "Show a real folder without moving files.",
        ["Onboarding.DropAction.MoveTitle"] = "Move",
        ["Onboarding.DropAction.MoveDescription"] = "Remove the original; store the file here.",
        ["Onboarding.DropAction.CopyTitle"] = "Copy",
        ["Onboarding.DropAction.CopyDescription"] = "Keep the original; add a copy here.",
        ["Onboarding.Storage.CurrentPath"] = "Default storage path",
        ["Onboarding.Storage.ChangePath"] = "Change path",
        ["Onboarding.Mapping.ManagedTitle"] = "Managed widget",
        ["Onboarding.Mapping.ManagedDescription"] = "Stores dropped files in DeskBox storage.",
        ["Onboarding.Mapping.MappedTitle"] = "Mapped widget",
        ["Onboarding.Mapping.MappedDescription"] = "Views a real folder in place.",
        ["Onboarding.Startup.Title"] = "Launch at startup",
        ["Onboarding.Startup.Description"] = "Start quietly after sign-in.",
        ["Onboarding.Scene.Desktop"] = "Windows desktop",
        ["Onboarding.Scene.DesktopFile"] = "Desktop file",
        ["Onboarding.Scene.ProjectFolder"] = "Project folder",
        ["Onboarding.Scene.ManagedWidget"] = "Managed widget",
        ["Onboarding.Scene.MappedWidget"] = "Mapped widget",
        ["Onboarding.Scene.DefaultStorage"] = "Storage path",
        ["Onboarding.Scene.OriginalFolder"] = "Real folder",
        ["Onboarding.Scene.NativeDesktop"] = "Desktop stays native",
        ["Onboarding.Scene.MoveBadge"] = "Move",
        ["Onboarding.Scene.CopyBadge"] = "Copy",
        ["Onboarding.Scene.ViewOnly"] = "View only",
        ["Onboarding.Scene.Startup"] = "Background start",
        ["Onboarding.Scene.StartupOff"] = "Manual start",

        ["Tray.Tooltip"] = "DeskBox desktop storage",
        ["Tray.TooltipRaised"] = "DeskBox desktop storage - widgets temporarily raised",
        ["Tray.TooltipNormal"] = "DeskBox desktop storage - left-click to raise widgets",
        ["Tray.ShowAll"] = "Show All Widgets",
        ["Tray.HideAll"] = "Hide All Widgets",
        ["Tray.Settings"] = "Settings",
        ["Tray.AutoStart"] = "Launch at Startup",
        ["Tray.Exit"] = "Exit",
        ["Widget.DefaultName"] = "New Managed Widget",
        ["Widget.DefaultNameShort"] = "New Widget",
        ["Widget.DefaultDesktopName"] = "My Desktop",
        ["Widget.ManagedFolderBaseName"] = "Managed Widget",
        ["Widget.NewFolderName"] = "New Folder",
        ["Widget.Mode.Managed"] = "Managed",
        ["Widget.Mode.Mapped"] = "Mapped",
        ["Widget.ModeInfo"] = "Widget type: {0} widget",
        ["Widget.Mode.ManagedDescription"] = "Managed widget. Dropped files are automatically organized into the default storage path.",
        ["Widget.Mode.MappedDescription"] = "Folder mapping widget. It directly displays the contents of a selected folder.",
        ["Widget.Empty.ManagedTitle"] = "Nothing stored yet",
        ["Widget.Empty.MappedTitle"] = "This folder is empty",
        ["Widget.Empty.ManagedText"] = "Drop files here and DeskBox will automatically {0} them to {1}.",
        ["Widget.Empty.MappedText"] = "Contents from {0} will appear here.",
        ["Widget.DragCaption.CurrentWidget"] = "Already in this widget",
        ["Widget.DragCaption.Managed"] = "{0} to managed widget",
        ["Widget.DragCaption.Reference"] = "Add to reference widget",
        ["Widget.Tooltip.Add"] = "New",
        ["Widget.Tooltip.More"] = "More options",
        ["Widget.Tooltip.DeleteWidget"] = "Delete widget",
        ["Widget.TitlePlaceholder"] = "Enter widget name",
        ["Widget.AddFile"] = "Add Files",
        ["Widget.ChangeMappedPath"] = "Change Mapped Path",
        ["Widget.IconView"] = "Icon View",
        ["Widget.ListView"] = "List View",
        ["Widget.LockPosition"] = "Lock Position",
        ["Widget.LockSize"] = "Lock Size",
        ["Widget.OpenCurrentFolder"] = "Open Current Folder",
        ["Widget.Open"] = "Open",
        ["Widget.ShowInExplorer"] = "Show in File Explorer",
        ["Widget.ItemCount"] = "{0} item(s)",
        ["Widget.CopyPathCount"] = "Copied {0} path(s)",
        ["Widget.SelectedCount"] = "{0} item(s) selected",
        ["Widget.MoveBackToDesktop"] = "Move Back to Desktop",
        ["Widget.MoveToDesktop"] = "Move to Desktop",
        ["Widget.MoveBackToDesktopFailed"] = "Move Back to Desktop Failed",
        ["Widget.MoveToDesktopFailed"] = "Move to Desktop Failed",
        ["Widget.NoItemsMoved"] = "No items were moved",
        ["Widget.CannotMoveToFolder"] = "Cannot move to this folder",
        ["Widget.CopyToFolder"] = "Copy to \"{0}\"",
        ["Widget.MoveToFolder"] = "Move to \"{0}\"",
        ["Widget.CopiedToFolder"] = "Copied {1} item(s) to {0}",
        ["Widget.MovedToFolder"] = "Moved {1} item(s) to {0}",
        ["Widget.MoveToFolderFailed"] = "Move to Folder Failed",
        ["Widget.AddedFile"] = "File added",
        ["Widget.AddedFiles"] = "{0} files added",
        ["Widget.AddFileFailed"] = "Add Files Failed",
        ["Widget.MappedPathUpdated"] = "Mapped path updated",
        ["Widget.ChangeMappedPathFailed"] = "Change Mapped Path Failed",
        ["Widget.CreateFolderFailed"] = "Create Folder Failed",
        ["Widget.DeleteFailed"] = "Delete Failed",
        ["Widget.RenameFailed"] = "Rename Failed",
        ["Widget.DeleteWidgetFailed"] = "Delete Widget Failed",
        ["Widget.PasteFailed"] = "Paste Failed",
        ["Widget.RefreshFailed"] = "Refresh Failed",
        ["Widget.NoCopyableItems"] = "No copyable items",
        ["Widget.CutCount"] = "Cut {0} item(s)",
        ["Widget.CopyCount"] = "Copied {0} item(s)",
        ["Widget.MovedCount"] = "Moved {0} item(s)",
        ["Widget.PastedCount"] = "Pasted {0} item(s)",
        ["Widget.Refreshed"] = "Refreshed",
        ["Widget.DeleteItemsTitleOne"] = "Move \"{0}\" to Recycle Bin?",
        ["Widget.DeleteItemsTitleMany"] = "Move {0} item(s) to Recycle Bin?",
        ["Widget.DeleteFolderNoteOne"] = "This is a folder. Its contents will also go to Recycle Bin.",
        ["Widget.DeleteFolderNoteMany"] = "This includes {0} folder(s). Folder contents will also go to Recycle Bin.",
        ["Widget.MoveToRecycleBin"] = "Move to Recycle Bin",
        ["Widget.MovedToRecycleBin"] = "Moved {0} item(s) to Recycle Bin",
        ["Widget.MovedBackToDesktop"] = "Moved {0} item(s) back to Desktop",
        ["Widget.MovedToDesktop"] = "Moved {0} item(s) to Desktop",
        ["Widget.DeleteWidgetTitle"] = "Delete \"{0}\"",
        ["Widget.DeleteWidgetNote"] = "Only remove the widget. Original files stay untouched.",
        ["Widget.DeleteWidgetConfirm"] = "Delete Widget",
        ["Widget.DeleteManagedInfo"] = "Choose how to handle the managed folder",
        ["Widget.KeepManagedFolder"] = "Keep managed folder",
        ["Widget.MoveBackThenDeleteFolder"] = "Move contents back, then delete empty folder",
        ["Widget.DeleteFolderToRecycleBin"] = "Delete folder and move files to Recycle Bin",
        ["Widget.Error.OperationIncomplete"] = "The operation did not complete.",
        ["Widget.Error.OperationCanceled"] = "The operation was canceled.",
        ["Widget.Error.AccessDenied"] = "DeskBox does not have permission to finish this operation.\n\n{0}",
        ["Widget.Error.FileInUse"] = "The file is being used by another app. Close the related app and try again.",
        ["Widget.Error.FileInUseWithPath"] = "The file is being used by another app. Close the related app and try again.\n\n{0}",
        ["Widget.Error.DuplicateName"] = "An item with the same name already exists at the destination.\n\n{0}",
        ["Widget.Validation.NameRequired"] = "Name cannot be empty.",
        ["Widget.Validation.FolderUnknown"] = "DeskBox could not determine the current item's folder.",
        ["Widget.Validation.TargetExists"] = "An item with that name already exists.",
        ["Widget.Error.ClipboardAllocate"] = "Could not allocate clipboard data.",
        ["Widget.Error.ClipboardWrite"] = "Could not write clipboard data.",
        ["Widget.Error.ManagedFolderCleanupOnlyDefault"] = "Only direct folders under the default storage path can be cleaned up.",
        ["Widget.Error.ManagedFolderStillActive"] = "This folder still belongs to an existing managed widget and cannot be cleaned up as orphaned.",
        ["Widget.Error.ManagedFolderActionOnlyDefault"] = "Only managed widgets under the default storage path can synchronize folder handling.",
        ["History.Title.CopyToManaged"] = "Copied to Managed Widget",
        ["History.Title.MoveToManaged"] = "Moved to Managed Widget",
        ["History.Title.MoveBackToDesktop"] = "Moved Back to Desktop",
        ["History.Title.DesktopOrganization"] = "Desktop Organization",
        ["History.CurrentWidget"] = "Current widget",
        ["History.NoItems"] = "No items were recorded.",
        ["History.ItemSummary"] = "{0} and {1} item(s)",
        ["History.UndoMoveBackToDesktop"] = "Undo Move Back to Desktop",
        ["History.UndoLastMove"] = "Undo Last Move",
        ["History.OperationFailed"] = "Operation failed",
        ["FileInfo.File"] = "File",
        ["FileInfo.FolderItems"] = "{0} items",
        ["FileInfo.FileModified"] = "{0} · {1:yyyy/M/d HH:mm}"
    };
}
